# Site settings
title: dataethos
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dataethos.github.io" # the base hostname & protocol for your site
twitter_username: dataethos
github_username:  dataethos
category-list: [cooking]
cooking-categories: [beef, breakfast, dessert, pork, "rice & noodles", seafood, soup]

# Build settings
markdown: kramdown
